plugins {
    id "com.github.node-gradle.node" version "7.1.0"
    id "run.halo.plugin.devtools" version "0.6.2"
    id "io.freefair.lombok" version "8.13"
    id 'java'
}

group = 'cn.aobp.wishboard'
version = project.findProperty('pluginVersion') ?: '0.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('run.halo.tools.platform:plugin:2.25.0')
    compileOnly 'run.halo.app:api'
    compileOnly 'run.halo.aifoundation:api:1.0.0'
    testImplementation 'run.halo.app:api'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework:spring-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
    options.compilerArgs << "-parameters"
}

processResources {
    filesMatching('plugin.yaml') {
        expand(pluginVersion: project.version)
    }
}

node {
    nodeProjectDir = file("${project.projectDir}/console")
}

tasks.register('buildFrontend', PnpmTask) {
    args = ['build']
    dependsOn('installDepsForUI')
}

tasks.register('installDepsForUI', PnpmTask) {
    args = ['install']
}

build {
    tasks.named('compileJava').configure {
        dependsOn('buildFrontend')
    }
}

halo {
    version = '2.25.0'
    superAdminUsername = 'admin'
    superAdminPassword = 'admin'
    externalUrl = 'http://localhost:8090'
    port = 8090
}
